### ISSUE TITLE
ISA-Tab logging is not working properly

### ISSUE THREAD

**Issue by pkrog** [phnmnl/galaxy#10]
I've updated `isa.py` to use the logging package, the same way do other data types:
```python
logger = logging.getLogger(__name__)
```
And I've added at least one information message in each method. But I'm only seeing the ones in the constructor:
```
galaxy.datatypes.isa INFO 2017-10-02 09:39:36,565 Isa::__init__ 01
galaxy.datatypes.isa INFO 2017-10-02 09:39:36,565 Isa::__init__ 02
galaxy.datatypes.isa INFO 2017-10-02 09:39:36,565 Isa::__init__ 01
galaxy.datatypes.isa INFO 2017-10-02 09:39:36,565 Isa::__init__ 02
galaxy.datatypes.isa INFO 2017-10-02 09:39:36,645 Isa::__init__ 01
galaxy.datatypes.isa INFO 2017-10-02 09:39:36,645 Isa::__init__ 02
galaxy.datatypes.isa INFO 2017-10-02 09:39:36,645 Isa::__init__ 01
galaxy.datatypes.isa INFO 2017-10-02 09:39:36,645 Isa::__init__ 02
```
When uploading a Metabolights study zip file with "Upload File" tool (specifying isa-tab type explicitly), no other messages are printed. Why?

**Comment by pkrog** [comment]
I'm running Galaxy under macOS.

**Comment by pkrog** [comment]
Tested with `MTBLS30.zip`.

**Comment by pkrog** [comment]
The right composite type had been commented out in `Isa` class. It was set to `'basic'` instead of `'auto_primary_file'`. Once corrected, Galaxy prints me the following error message:
```
Traceback (most recent call last):
  File "/home/pierrick/dev/galaxy-isatab/tools/data_source/upload.py", line 491, in <module>
    __main__()
  File "/home/pierrick/dev/galaxy-isatab/tools/data_source/upload.py", line 477, in __main__
    add_composite_file(dataset, registry, json_file, output_path, files_path)
  File "/home/pierrick/dev/galaxy-isatab/tools/data_source/upload.py", line 432, in add_composite_file
    datatype.write_from_stream(dataset, input_stream)
  File "/home/pierrick/dev/galaxy-isatab/lib/galaxy/datatypes/isa.py", line 106, in write_from_stream
    tmp_folder = self._extract_archive(stream)
  File "/home/pierrick/dev/galaxy-isatab/lib/galaxy/datatypes/isa.py", line 69, in _extract_archive
    raise Exception("Not supported archive format!!!")
Exception: Not supported archive format!!!
```

**Comment by pkrog** [comment]
When uploading zip file with Firefox under Linux/Ubuntu, the first characters of the file are <htm instead of the magic number for a ZIP file (4b50 0403).

**Comment by pkrog** [comment]
The header of the dataset is:
```
<html><head><title>Wiff Composite Dataset </title></head><p/>
<div>This composite dataset is compose...
```
It seems the zip file is detected as another type of dataset when loaded, despite the fact that I specify Isa-Tab inside the uploader.

**Comment by kikkomep** [comment]
6b9a71898034b11e32fa02c4818596c76c27ec7d allows to use a standard Python logger, properly configured to use the standard output as output channel. Notice that log messages are split between the main Galaxy log file and the standard output produced by tools (see "dataset details" > "Job information" > "Tool Standard Output")

**Comment by kikkomep** [comment]
94b3ed4e1fbe9d884e88775d626c8a379daecb79, 124286d3af91092ae3456b3bad254dafb1b0fe54 and the uploader updates in feature/uploader-improvements branch enable the `auto_primary_file` type of the ISA composite datatype

**Comment by kikkomep** [comment]
b630f1ac559e02819518dd1b5d4d4801c8835697 fixes the wrong header of the primary file.

**Comment by pkrog** [comment]
I close this issue. Logging is working, even if it is in a strange way (first part into the console, second part into the uploader output).
