### ISSUE TITLE
ISA-Tab no primary file displayed

### ISSUE THREAD

**Issue by pkrog** [phnmnl/galaxy#11]
Once a study has been imported in Galaxy, if I click on the "View data" icon, nothing is displayed. Instead, the browser download the investigation file with an encoded name (e.g.: Bq1h32eJ) without extension.
Tested under Safari and Firefox.

**Comment by pkrog** [comment]
Tested with `MTBLS30.zip`.

**Comment by kikkomep** [comment]
39e80a435cd8100c5f50d744a5ff3af1f843d04e introduces an initial implementation of history peek for ISA datasets. The whole investigation file is displayed at the moment.

**Comment by pkrog** [comment]
I've had an issue with `_move_to_target_path()` not copying all the files. I've corrected the `elif len(tmp_subfolders) > 1:` part, and now it's working for me. I'm pushing now my modifications along some new debug output.
Still, the primary file is not displayed when clicking on the eye icon. Is it normal? For HTML composite files it is displayed. Does it work for you?

**Comment by pkrog** [comment]
The `_extract_archive()` method is called after `get_primary_file()`, so my correction has no effect on the files listed by `get_primary_file()`. Moreover, `get_primary_file()` gets its files from `get_composite_files()` which is only filled with 'archive' file name: is it normal? Should not we have all files listed inside this composite files list?

**Comment by kikkomep** [comment]
The fix of the `_move_to_target_path()` method is OK!
To enable "View Data" functionality (i.e., the "eye icon") an implementation of the `display_data` method is required. The last three commits (e5412a246d51aa0fb2747cf66b681e614183811c, 28c0a3d700a036d33dd8768ff11ae8def21928fb, d81413e0ce7b5d95c28ee7f20adca20619a211b7) introduce an _initial_ support for the "View Data" functionality: it uses a tabular template which needs to be customise to better display data.

**Comment by pkrog** [comment]
Yes I've seen that  this requires `display_data()`. I'll get the three commits.

**Comment by pkrog** [comment]
Thanks for the work. This is great job!
However I don't think the investigation file is what people want to get.
It would be better to have the display of an HTML page that presents nicely the content of the study: where it comes from, date created, list of assays, etc. And then present links towards the i_* file, the a_* files, the s_* files and the m_* files so people can look into them. If you don't mind, I'll take care of this display part from this point, in a parallel branch, but I reserve the right to ask your help :-) in case I need your proven expertise in Galaxy code.

**Comment by kikkomep** [comment]
Ok, Pierrick! Let me know.

**Comment by pkrog** [comment]
Hi @kikkomep , @djcomlab , @ilveroluca , @pcm32 
In order to display information on the ISA dataset, I was thinking on using the isatools python library in Galaxy and get advantage of the parsers for both JSON and TAB formats.
The other solutions would be to look for information by myself in the JSON file or the tabular investigation file, but it would be less maintainable.
Do you think this is unreasonable to propose adding isatools to Galaxy? I've looked inside the requirements.txt file, and it seems that they try not to add any bio library at this level.

**Comment by djcomlab** [comment]
Does Galaxy have any bio-format readers/writers?

**Comment by pkrog** [comment]
They should have had some, since Galaxy has been developed for genetics. However I cannot find parser modules for sequence data. For instance in the datatypes contained in <https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/assembly.py>, they parse lots of FASTA files. FASTA is quite standard in genomics. Still they do it "by hand", not using an already developed Python module.

**Comment by pkrog** [comment]
Certainly, if we want to maximize our chance to have this new ISA datatype integrated in Galaxy code, we need to stick to already existing code. However I find that weird to recode parsing of established formats, when modules that do the job exist.

**Comment by djcomlab** [comment]
I agree. even with the FASTA example, they have SeqIO as part of the biopython package... 

I don't think it's unreasonable to ask, but if they have a concrete reason for keeping third-party bio-related packages outside then it would be good to know why they have this policy, and then we can decide what to do next.

**Comment by pkrog** [comment]
Ok, then I'll write a message on the original issue opened by @pcm32 on the Galaxy project GitHub: galaxyproject/galaxy#3134

**Comment by djcomlab** [comment]
If in the end we have to duplicate some code and put code directly into Galaxy itself, am sure we are happy to help with this effort.

**Comment by pkrog** [comment]
I think all information contained in `i_investigation.txt` for the ISA-Tab version should be accessible in the Python2.7 version. And at least the same information for the ISA-Json version.
I'm going to make a minimal version, without isatools, for the end of the week, since I need to deliver for October 30. Then I will improve it a bit when isatools is available for Python2.7. But I guess users will want a maximum of information at some point, so it is better to target the whole investigation file.

**Comment by djcomlab** [comment]
OK, but just to clarify, `isatools` there is no plan to be available for Python 2.7. If you need an ISA-Tab and ISA JSON reader only for Python 2.7, I can probably relatively quickly do that.

**Comment by pkrog** [comment]
That's what I meant, I understood isatools is not going to be compatible with Python2.7. And you can restrict to the information included inside the investigation file.

**Comment by djcomlab** [comment]
OK give me a couple of days, I'll make a `isatools-lite`. Will that suit your delivery schedule?

**Comment by pkrog** [comment]
Yes it will, thanks David.

**Comment by djcomlab** [comment]
Hi, there's now a slimmed down ISA API here:

https://github.com/ISA-tools/isa-api/tree/py2_isatools-lite

tested on py27 and py34+.

The ISA-Tab parser should now work like:

```
parser = isatab.Parser()
parser.parse('/path/to/i_investigation.txt')
investigation_object = parser.isa
# the use objects as before
study = investigation_object.studies[0]
for sample in study.samples:
    print sample  # etc...
```

I've not got it to push to PyPI yet but just install from source with `pip install -e` for now to try it.

**Comment by djcomlab** [comment]
p.s. refer to the tests for further indications of usage.

**Comment by pkrog** [comment]
Hi David, thanks for that. I'm going to try it this week-end, and I will keep you informed on Monday.

**Comment by djcomlab** [comment]
We have forked the galaxy datatype project into the main ISA-tools org if you want to contribute directly there https://github.com/ISA-tools/galaxy.datatypes.isa

I've added an example of how to use the new lite `isatools` in there (but not quite sure how to test it really), but I think it gives the idea how to use it.

**Comment by kikkomep** [comment]
Hi @djcomlab,
the project you’ve forked is now obsolete. I’ve moved all the code into the feature/isa-datatype branch of the phnmnl/galaxy repo, where also Pierrick is pushing his contributions.

Thank you for your example (https://github.com/kikkomep/galaxy.datatypes.isa/pull/1/commits/08da2c1430c098005f664a7ba0227c63e79fcffc): it might be useful for displaying info about ISA datasets within Galaxy.

**Comment by djcomlab** [comment]
Hi @kikkomep OK thanks! In discussion with Pierrick our preference would be to try and use the ISA API in the data type implementation, so our team is happy to review the implementation and I can help wherever appropriate.

**Comment by pkrog** [comment]
Hi @djcomlab @kikkomep , I've opened an issue ISA-tools/isa-api#253 about Pandas and NumPy I have on both macOS and Linux. Tell me if you have any ideas about the reason.

**Comment by djcomlab** [comment]
@pkrog Yes I did reply to your issue already

**Comment by pkrog** [comment]
@djcomlab , the loading of the library seems to work now. Except that it produces lots of debug messages with a logger when the uploader tool is run:
```
DEBUG:galaxy.datatypes.registry:Retrieved datatype module galaxy.datatypes.isa:Isa from the datatype registry.
DEBUG:galaxy.datatypes.registry:Retrieved datatype module galaxy.datatypes.tabular:Tabular from the datatype registry.
DEBUG:galaxy.datatypes.registry:Retrieved datatype module galaxy.datatypes.data:Text from the datatype registry.
DEBUG:galaxy.datatypes.registry:Retrieved datatype module galaxy.datatypes.data:Text from the datatype registry.
...
```
This makes the tool to fail, since in Galaxy a tool fails at the end if anything was output at stderr.
Could you fix the logger in isatools, and make it silent by default?

**Comment by ilveroluca** [comment]
@pkrog, it might be better to configure the module's logger to send its output to `stdout` instead of `stderr` in your client code. While you're at it you can also lower the default log level to something less than `DEBUG` :-)

That would avoid having a situation where there's a problem but we don't get any error messages because we killed ISA's logger.

**Comment by djcomlab** [comment]
The default logging should already be set to ERROR in the `isatools` package. Are you sure the DEBUG is not coming from somewhere else?

**Comment by djcomlab** [comment]
Also note that these particular DEBUG messages are not generated by the `isatools` code anyway.

**Comment by djcomlab** [comment]
Actually found I had not reset the log level. Please pull the latest and try again.

**Comment by pkrog** [comment]
If I comment out the two import lines, stderr is quiet:
```
#from isatools import isatab
#from isatools import isajson
```

**Comment by pkrog** [comment]
Ok, I'll try the new version.

**Comment by pkrog** [comment]
Yes, that works, thanks.

**Comment by pkrog** [comment]
Hi @djcomlab,
In `isatab2w4m` I use `isatab.load(file)` to load an investigation file. The load method has disappeared in `py2_isatools-lite`.  How should I do now to load a ISA-Json or ISA-Tab?

**Comment by pkrog** [comment]
Ok, I've seen the example you've written, I'll copy code from it.

**Comment by pkrog** [comment]
We have a display of information now when clicking on "View data" icon.
