### ISSUE TITLE
ISA-Tab/ISA-Json code merging

### ISSUE THREAD

**Issue by pkrog** [phnmnl/galaxy#12]
The distinction between IsaTab and IsaJson, does not seem pertinent from the point of view of the user.
How the user could know how to choose between IsaTab and IsaJson from inside the "Upload File" Galaxy tool, since he blindly uploads a zip file? We should try to have only one ISA class and handle Tab/Json file types inside.

**Comment by kikkomep** [comment]
9fe7b8b858c9c7f0f3337a0b49a433685e4b3447, 2d4275ed551cfe87b5590060d368cf951ad137d3, 334efeab885a3d42ffa063507bae0459456f7dda and 334efeab885a3d42ffa063507bae0459456f7dda move the core logic to the main Isa class and allow to define a generic `isa` datatype able to handle either ISA-Tab and ISA-JSON.
The two more specific `isa-tab` and `isa-json` are maintained at the moment.

**Comment by kikkomep** [comment]
@pkrog Can we close this issue, right?

**Comment by pkrog** [comment]
Right, it has been done.
