### ISSUE TITLE
Generation of primary file in ISA datatype 

### ISSUE THREAD

**Issue by pkrog** [phnmnl/galaxy#17]
The generated primary file contains only basic information, and only list the filename of the archive file (ZIP file).
Could the archive file be extracted earlier in the process? It is currently extracted inside the `groom_dataset_content()` method, but I wonder if this is the right place.

**Comment by kikkomep** [comment]
The branch [fix/meaningful-isa-datatype-primaryfile](https://github.com/phnmnl/galaxy/tree/fix/meaningful-isa-datatype-primaryfile) contains an update of the `generate_primary_file` procedure which allows to generate a meaningful primary file, i.e., a list of all the files within the dataset.

The `groom_dataset_content` is called immediately after the upload of the archive file as a final step of the uploader tool.

**Comment by pkrog** [comment]
Done
