### ISSUE TITLE
ISA-Tab type

### ISSUE THREAD

**Issue by pkrog** [phnmnl/galaxy#9]
Hi @kikkomep , could you explain a bit how your new type works?
I've assumed I have to upload a zipped MTBLS study through the uploader, and that the containt will be detected as ISA-Tab. Am I right?

**Comment by kikkomep** [comment]
Yes @pierrickrogermele. If you install the isa-tab datatype (and the related uploader patch) you will be able to select “isa-tab” as type of the dataset to upload. Your zipped MTBLS study will be therefore detected as ISA-Tab, i.e., as a composite datatype constituted by a primary file (at the moment, the investigation file) and a related folder containing all the actual files of the uploaded ISA dataset.

**Comment by pkrog** [comment]
I've switched to branch feature/isa-datatype, and run galaxy (./run.sh). But I can't see "isa-tab" in the list of the dataset types in the uploader. Could you please explain me what I am missing?

**Comment by kikkomep** [comment]
You have to register the two datatypes using the `config/datatypes_conf.xml` configuration file. 
In detail, you have to add the following elements as children of the `registration` element:
```
<datatype extension="isa-tab" type="galaxy.datatypes.isa:IsaTab" mimetype="application/isa-tools"
                  display_in_upload="true" description="ISA-Tab data type." description_url="https://isa-tools.org"/>
<datatype extension="isa-json" type="galaxy.datatypes.isa:IsaJson" mimetype="application/isa-tools"
                  display_in_upload="true" description="ISA-JSON data type." description_url="https://isa-tools.org"/>
```

... and the following elements as children of the `sniffers`element:
```
<sniffer type="galaxy.datatypes.isa:IsaTab"/>
<sniffer type="galaxy.datatypes.isa:IsaJson"/>
```

**Comment by pkrog** [comment]
Ah ! ok, thanks.

**Comment by pkrog** [comment]
Could we put that code inside a `datatypes_phnmnl_conf.xml.sample`, so it's easier to setup?

**Comment by pkrog** [comment]
I got the following error:
Traceback (most recent call last):
```
  File "/Users/pierrick/dev/galaxy/lib/galaxy/webapps/galaxy/buildapp.py", line 58, in paste_app_factory
    app = galaxy.app.UniverseApplication( global_conf=global_conf, **kwargs )
  File "/Users/pierrick/dev/galaxy/lib/galaxy/app.py", line 114, in __init__
    self.datatypes_registry.load_display_applications( self )
  File "/Users/pierrick/dev/galaxy/lib/galaxy/datatypes/registry.py", line 639, in load_display_applications
    current_app = d_type1.get_display_application( display_app.id, None )
  File "/Users/pierrick/dev/galaxy/lib/galaxy/datatypes/data.py", line 453, in get_display_application
    return self.display_applications.get( key, default )
AttributeError: 'IsaJson' object has no attribute 'display_applications'
```
Any idea?

**Comment by kikkomep** [comment]
I think that your local branch is out of sync. Try to do a rebase.

**Comment by pkrog** [comment]
That works, thanks.
Now in Galaxy, while trying to upload MTBLS30, I get the following output and error:

```
DEBUG: Detected file type: zip (prefix: 'PK\x03\x04')
DEBUG: Decompressing the ZIP archive
DEBUG: Setting metadata of ISA type: /Users/pierrick/dev/galaxy-isatab/database/files/000/dataset_1.dat
```

```
Traceback (most recent call last):
  File "/Users/pierrick/dev/galaxy-isatab/tools/data_source/upload.py", line 491, in <module>
    __main__()
  File "/Users/pierrick/dev/galaxy-isatab/tools/data_source/upload.py", line 477, in __main__
    add_composite_file(dataset, registry, json_file, output_path, files_path)
  File "/Users/pierrick/dev/galaxy-isatab/tools/data_source/upload.py", line 432, in add_composite_file
    datatype.write_from_stream(dataset, input_stream)
  File "/Users/pierrick/dev/galaxy-isatab/lib/galaxy/datatypes/isa.py", line 139, in write_from_stream
    for f in os.listdir(os.path.join(tmp_folder)):
OSError: [Errno 2] No such file or directory: '/var/folders/7d/w7hn4fxs0158ttnq01yl665m0000gn/T/tmpjKdaUP'
```

**Comment by kikkomep** [comment]
Ok, fixed! In line 139 there was a reference to a moved folder. Try again to do a rebase.

**Comment by pkrog** [comment]
Thank you Marco, It works now.

**Comment by pkrog** [comment]
Hi Marco,

I've pushed a branch (feature/isa-datatype-conf) with modified `datatypes_conf.xml.sample` containing the isatab config lines. You can  merge it in `feature/isa-datatype` if you wish.

In `isa.py`, you use a small logger class, certainly for debug purposes. Don't you think we should already the Galaxy logging mechanism? From `blast.py`, I've seen it's quite simple:
```python
import logging
log = logging.getLogger(__name__)
...
log.warning("BLAST XML file %s missing, retry in 1s..." % f)
```
What do you think? I can do it if you're ok.

**Comment by pkrog** [comment]
About the distinction between IsaTab and IsaJson, I'm not sure this is pertinent. How the user could now how to choose between IsaTab and IsaJson, since he blindly upload a zip file? We should have only one ISA class and handle Tab/Json file types inside, if possible.

**Comment by kikkomep** [comment]
Hi @pierrickrogermele ! 
The ISA datatype configuration that you've proposed in `feature/isa-datatype-conf` has been merge in `feature/isa-datatype`... thus that branch can be deleted.
As you've rightly said in https://github.com/phnmnl/galaxy/issues/9#issuecomment-324915409, the small logger class is only for debug purposes... You can surely update the logger initialization to use the standard Galaxy logging facilities.

**Comment by RJMW** [comment]
@pierrickrogermele @kikkomep Great work!

Are you both aware of https://github.com/phnmnl/container-mzml2isa and https://github.com/phnmnl/container-nmrml2isa

Would be great if we can test the new ISA-TAB datatype with both tools at some point (we probably need to update the tools to include the data types). Are there any plans to include the ISA-TAB datatype also in the general list of galaxy data types (https://galaxyproject.org/learn/datatypes)?

(@Tomnl - FYI).

**Comment by pkrog** [comment]
Hi @RJMW ,

Sorry for my very late answer to your post.
Yes, our goal is to integrate our developments into the official Galaxy project. We aim at handling both ISA-Tab and ISA-Json formats.

We have an objective very similar to the container you're talking about, with the Metabolights downloader. We have to output an ISA datatype too from a Metabolights study. Keep an eye on issue #14  to be informed about the advancement of this task.

Best regards,
